# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'records.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_Form(object):
    def __init__(self):
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        #ui = Ui_Form()
        self.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 341, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "records"))


if __name__ == "__main__":
 #   app = QtWidgets.QApplication(sys.argv)
  #  Form = QtWidgets.QWidget()
   # ui = Ui_Form()
    #ui.setupUi(Form)
    #Form.show()
    #sys.exit(app.exec_())
    wid = Ui_Form()